In [121]:
import numpy as np
import pandas as pd

In [122]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [123]:
df = pd.read_csv('independent-house - independent-house.csv')

In [124]:
df.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
322,4 Bedroom House for sale in Jyoti Park,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,1.35 Crore,"₹ 40,909/sq.ft.",(31 sq.m.) Built-up Area,Built Up area: 330 (30.66 sq.m.),4 Bedrooms,5 Bathrooms,No Balcony,NaN,"Jyoti Park, Sector 7, Jyoti Park, Gurgaon, Har...",3 Floors,NaN,undefined,NaN,"5 bath, furnished, ground floor (Of 3), jyoti ...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",M69535664
214,6 Bedroom House for sale in Madanpuri,https://www.99acres.com/6-bhk-bedroom-independ...,NaN,90 Lac,"₹ 10,000/sq.ft.",(84 sq.m.) Plot Area,Plot area 100(83.61 sq.m.),6 Bedrooms,4 Bathrooms,3 Balconies,"Servant Room,Others","Madanpuri, Gurgaon, Haryana",3 Floors,North-East,10+ Year Old,"['Dev Man Kathuria Clinic', 'Dr. Madan Clinic'...","Corner property, two side open, 30 by 30 with ...","['5 Fan', '1 Exhaust Fan', '1 Geyser', '6 Ligh...","['Feng Shui / Vaastu Compliant', 'Water Storag...","['Environment4 out of 5', 'Lifestyle4 out of 5...",S70077862
375,4 Bedroom House for sale in Arjun Nagar,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,1.6 Crore,"₹ 28,674/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),4 Bedrooms,6 Bathrooms,1 Balcony,NaN,"Arjun Nagar, Gurgaon, Haryana",3 Floors,NaN,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",W69287014
749,5 Bedroom House for sale in Sushant Lok Phase 3,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,8.31 Crore,"₹ 24,171/sq.ft.",(319 sq.m.) Plot Area,Plot area 382(319.4 sq.m.),5 Bedrooms,6 Bathrooms,3+ Balconies,"Store Room,Pooja Room,Servant Room,Study Room","Corner Villa, Sushant Lok Phase 3, Gurgaon, Ha...",4 Floors,North-East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...","Sushant lok-3\nBlock-B, corner villa at plot r...",[],"['Feng Shui / Vaastu Compliant', 'False Ceilin...","['Environment4 out of 5', 'Lifestyle4 out of 5...",E69994668
238,8 Bedroom House for sale in DLF Phase 1,https://www.99acres.com/8-bhk-bedroom-independ...,NaN,6 Crore,"₹ 33,333/sq.ft.",(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),8 Bedrooms,5 Bathrooms,3+ Balconies,NaN,"DLF Phase 1, Gurgaon, Haryana",3 Floors,NaN,10+ Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",Interested to sell independent house/villa.It ...,"['8 Bed', '8 Wardrobe', '5 Geyser', '10 AC', '...",['Private Garden / Terrace'],"['Environment5 out of 5', 'Lifestyle5 out of 5...",G62798362

In [125]:
df.shape

(1095, 21)

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   object
 1   link             1095 non-null   object
 2   society          471 non-null    object
 3   price            968 non-null    object
 4   rate             1054 non-null   object
 5   area             1095 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 179.8+ KB

In [127]:
df.duplicated().sum()

13

In [128]:
df = df.drop_duplicates()

In [129]:
df.duplicated().sum()

0

In [130]:
df.shape

(1082, 21)

In [131]:
df.isnull().sum()

property_name        0
link                 0
society            619
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     504
address             64
noOfFloor          127
facing             420
agePossession      108
nearbyLocations    182
description         59
furnishDetails     350
features           420
rating             188
property_id         59
dtype: int64

In [132]:
df.drop(columns=['link'], inplace=True)

In [133]:
df.shape

(1082, 20)

In [134]:
df.rename(columns={'noOfFloor':'floorNum'}, inplace = True)

In [135]:
df.rename(columns={'rate':'price_per_sqft'}, inplace = True)

In [136]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [137]:
df.sample(10)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
589,4 Bedroom House for sale in Sector 1 Gurgaon,NaN,1.85 Crore,"₹ 16,003/sq.ft.",(107 sq.m.) Carpet Area,Carpet area: 1156 (107.4 sq.m.),4 Bedrooms,3 Bathrooms,2 Balconies,NaN,"975 Friends Colony, Sector 1 Gurgaon, Gurgaon,...",3 Floors,NaN,undefined,NaN,4bhk residential house for resale in sector 1 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN,A67903828
519,4 Bedroom House for sale in DLF Phase 3,NaN,3.25 Crore,"₹ 30,384/sq.ft.",(99 sq.m.) Plot Area,Plot area 1069.63(99.37 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,NaN,"DLF Phase 3, Gurgaon, Haryana",3 Floors,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Interested to sell independent house/villa.It ...,NaN,"['Water Storage', 'Park']","['Environment4 out of 5', 'Lifestyle5 out of 5...",U55815156
250,5 Bedroom House for sale in Sector 33 Gurgaon,Unitech Uniworld Resorts,9.5 Crore,"₹ 23,333/sq.ft.",(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),5 Bedrooms,7 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Sector 33 Gurgaon, Gurgaon, Haryana",2 Floors,East,Dec 2023,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",It is east facing villa. The possession is tak...,NaN,"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment3 out of 5', 'Lifestyle4 out of 5...",Y69896412
290,9 Bedroom House for sale in Sheetla Colony,NaN,1.65 Crore,"₹ 75,000/sq.ft.",(20 sq.m.) Built-up Area,Built Up area: 220 (20.44 sq.m.),9 Bedrooms,9 Bathrooms,No Balcony,NaN,"Sheetla Colony, Sheetla Colony, Gurgaon, Haryana",1 Floors,NaN,0 to 1 Year Old,NaN,Best in class property available at sheetla co...,"['1 Wardrobe', '1 Light', 'No AC', 'No Bed', '...",NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5...",Q69720450
997,10 Bedroom House for sale in South City 1,NaN,4.25 Crore,"₹ 26,235/sq.ft.",(151 sq.m.) Plot Area,Plot area 180(150.5 sq.m.),10 Bedrooms,9 Bathrooms,3+ Balconies,"Study Room,Servant Room","South City 1, Gurgaon, Haryana",4 Floors,North,5 to 10 Year Old,"['Huda city centre metro station', 'Axis bank ...",Old floor wise building for sale in south city...,"['5 Fan', '5 Geyser', '1 Microwave', '21 Light...","['Water Storage', 'No open drainage around', '...","['Environment5 out of 5', 'Safety5 out of 5', ...",P68645382
574,5 Bedroom House for sale in New Colony,Rattan Garden,83 Lac,"₹ 17,584/sq.ft.",(44 sq.m.) Carpet Area,Carpet area: 472 (43.85 sq.m.),5 Bedrooms,3 Bathrooms,2 Balconies,NaN,"394/1/11, Rattan Garden, New Colony, New Colon...",3 Floors,East,undefined,"['Chintapurni Mandir', 'Aryan Hospital', 'D.R....",5bhk residential house for resale in rattan ga...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",I67904354
717,4 Bedroom House for sale in DLF Phase 1,NaN,8.9 Crore,"₹ 32,963/sq.ft.",(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room,Pooja Room,Store Room","Xyz, DLF Phase 1, Gurgaon, Haryana",2 Floors,South-East,10+ Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",Lucrative distress deal available for sale kot...,"['9 Fan', '10 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",I66317624
389,5 Bedroom House for sale in Block G Sector-57 ...,NaN,1.35 Crore,"₹ 24,545/sq.ft.",(51 sq.m.) Plot Area,Plot area 550(51.1 sq.m.),5 Bedrooms,3 Bathrooms,2 Balconies,NaN,"G1139, Block G Sector-57 Gurgaon, Gurgaon, Har...",3 Floors,South-East,10+ Year Old,"['Sector metro station', 'Sector metro station...","Posh location, nice locality. Independent hous...","['1 Water Purifier', '1 Fan', '1 Light', '1 Wa...","['Maintenance Staff', 'Park', 'Visitor Parking']",NaN,I69155560
607,1 Bedroom House for sale in Sector 110 Gurgaon,NaN,34 Lac,"₹ 6,800/sq.ft.",(46 sq.m.) Built-up Area,Built Up area: 500 (46.45 sq.m.),1 Bedroom,1 Bathroom,No Balcony,NaN,"Nihali Colony, Sector 110, Gurgaon, Sector 110...",1 Floors,NaN,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",One of the finest property in sector 110 is no...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",T67766782
1092,8 Bedroom House for sale in DLF Phase 2,NaN,NaN,"₹ 23,457/sq.ft.",(376 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [138]:
df['society'].value_counts()

society
International City by SOBHA Phase 2                  26
Emaar MGF Marbella                                   26
Vipul Tatvam Villa                                   25
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             14
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Unitech Espace                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Uppal Southend4.0 ★                                   8
Not Applicable                                        7
Ansals Palam Vihar                                    6
Sushant Lok 1 Builder Floors                          6
Experion Windchants3.8 ★                              5
DLF City Phase 1                                      5
Vatika India Next4.1 ★                                4
nul                                                   4
Unitech Nirvana Birch Court                           4
Ansal Sushant Lok Plots4.1 ★                          4
DLF Alameda                                           4
Ansals Florence Villa                                 4
Unitech Aspen Greens                                  4
DLF New Town Heights 24.0 ★                           4
Vatika Signature Villas                               3
Eros Rosewood City4.0 ★                               3
Sector 14 RWA                                         3
Eros Rosewood Villas                                  3
Palam Vihar Extension West Zone RWA                   3
Malibu Towne                                          3
Housing Board Colony                                  3
BPTP Astaire Gardens3.7 ★                             3
Rattan Garden                                         3
Hans Enclave                                          3
HUDA Ashok Vihar Phase 13.9 ★                         3
Bestech Park View Ananda4.2 ★                         3
SS Aaron Ville                                        3
Silverglades Tarudhan Valley Golf Resort              3
Tata Primanti4.1 ★                                    3
Puri Diplomatic Greens4.0 ★                           3
Central Park Flower Valley                            3
DLF City Plots Phase 3                                3
Anant Raj Estates                                     3
Suncity Essel Towers4.2 ★                             2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Sobha City                                            2
DLF South City 1                                      2
Ansal Sushant Residency                               2
Ardee City3.8 ★                                       2
Signature Global City 92                              2
Satya The Hermitage3.5 ★                              2
Suncity Township4.1 ★                                 2
Unitech Deerwood Chase                                2
Emaar The Palm Springs                                2
Project Mianwali Colony                               2
Nirvana Cedar Crest                                   2
Ansal API Esencia3.7 ★                                2
SS Hibiscus                                           2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
Luxury DLF City Floors                                2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Project Housing Board Colony                          2
Unitech Escape3.8 ★                                   2
DLF City Plots Phase 4                                2
Emaar Emerald Hills4.1 ★                              2
shivpuri                                              2
Spaze Privy3.9 ★                                      2
Om Nagar, Sector-11                                   1
Ireo Victory Valley4.1 ★                              1
Grover Homes Sec 4                                    1
4S Aradhya Homes                                      1
Ansal API Spanish Court                               1
secter 16a daultabad faridabad house no 313           1
Central Park Flower Valley Cerise Floors              1
FLOOR WISE DESIGNER KOTHI                             1
Birla Navya                                           1
Kothi                                                 1
rajendra park sec 105                                 1
nirvana country                                       1
Landmark House                                        1
Smart World Orchard                                   1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal                                                 1
Ashok vihar phase III Extension                       1
Ansal Heights3.2 ★                                    1
rattan vihar rajendra park                            1
Signature Global City 63A                             1
DLF City Plot Phase 3                                 1
Adani Brahma Samsara4.2 ★                             1
sneh vihar                                            1
Ansal Florence Super                                  1
Unitech South City 23.8 ★                             1
Suncity Avenue 76                                     1
patel nager house no 927/5                            1
Huda Floor                                            1
Huda                                                  1
Anant Raj Manor Villas                                1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Sector-17C                                            1
DLF Pink Town House4.0 ★                              1
huda sector-56 gurgaon                                1
Satya The Legend3.8 ★                                 1
Prem Kunj                                             1
Ireo Victory Valley4.0 ★                              1
Independent House Sector 45                           1
Ashok Vihar Phase 3 Gurgaon                           1
Farrukhnagar                                          1
Unitech Greenwood City3.6 ★                           1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF Floors Phase 3                                    1
Sheetla Enclave                                       1
SS Omnia                                              1
Bhawani enclave                                       1
Rajendra Park Gurgaon                                 1
Surat nagar phase 2                                   1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
DLF Gardencity Enclave                                1
RK Excelo                                             1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
house number B-34                                     1
Ansal Celebrity Homes                                 1
ATS Tourmaline3.9 ★                                   1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Laxman vihar phase 2                                  1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Emaar MGF The Palm Drive4.1 ★                         1
All Punjabi Welfare Association                       1
Tulip Ivory3.5 ★                                      1
Huda Plots                                            1
DLF Garden City Floors                                1
DLF The Arbour                                        1
Laxmi Garden Sector-11                                1
Shri Shyam Residency                                  1
Anshul                                                1
private house                                         1
Sare Crescent Parc Royal Greens Phase 1               1
Ninex City                                            1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
sector 37                                             1
Shivaji Nagar Residential                             1
Bhim Nagar Society                                    1
DLF City Plot Phase 4                                 1
mian wali                                             1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Krishna Palace                                        1
DLF New Town Heights3.7 ★                             1
Huda Flats                                            1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Madan puri                                            1
Signature Global Park4.0 ★                            1
ROW HOUSE                                             1
HUDA Plot Sector 38                                   1
My Home                                               1
HUDA Housing Board Colony4.1 ★                        1
Name: count, dtype: int64

In [139]:
df['society'].value_counts().shape

(188,)

In [140]:
import re

In [141]:
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [142]:
df['society'].value_counts()

society
nan                                                  619
emaar mgf marbella                                    26
international city by sobha phase 2                   26
vipul tatvam villa                                    25
international city by sobha phase 1                   23
unitech uniworld resorts                              14
dlf city plots phase 2                                11
unitech espace                                        11
dlf city plots                                        11
eldeco mansionz                                        9
bptp visionnaire                                       8
uppal southend                                         8
not applicable                                         7
sushant lok 1 builder floors                           6
ansals palam vihar                                     6
experion windchants                                    5
dlf city phase 1                                       5
dlf new town heights                                   5
dlf alameda                                            4
unitech nirvana birch court                            4
unitech aspen greens                                   4
ansals florence villa                                  4
nul                                                    4
vatika india next                                      4
ansal sushant lok plots                                4
eros rosewood villas                                   3
bptp astaire gardens                                   3
bestech park view ananda                               3
huda ashok vihar phase                                 3
hans enclave                                           3
housing board colony                                   3
eros rosewood city                                     3
palam vihar extension west zone rwa                    3
malibu towne                                           3
sector 14 rwa                                          3
vatika signature villas                                3
ss aaron ville                                         3
rattan garden                                          3
silverglades tarudhan valley golf resort               3
tata primanti                                          3
puri diplomatic greens                                 3
dlf city plots phase 3                                 3
central park flower valley                             3
anant raj estates                                      3
nirvana country                                        2
iffco nagar and 17b rwa                                2
bhim garh kheri                                        2
sobha city                                             2
dlf south city 1                                       2
ardee city                                             2
ansal sushant residency                                2
unitech escape                                         2
satya the hermitage                                    2
suncity township                                       2
suncity essel towers                                   2
unitech deerwood chase                                 2
emaar the palm springs                                 2
project housing board colony                           2
ansal api esencia                                      2
ireo victory valley                                    2
ss hibiscus                                            2
saksham welfare association                            2
unitech palms south city 1                             2
bptp pedestal                                          2
luxury dlf city floors                                 2
rwa sector 46                                          2
sector 38 rwa                                          2
nirvana cedar crest                                    2
signature global city 92                               2
dlf city plots phase 4                                 2
project mianwali colony                                2
emaar emerald hills                                    2
spaze privy                                            2
shivpuri                                               2
ninex city                                             1
grover homes sec 4                                     1
4s aradhya homes                                       1
ansal api spanish court                                1
central park flower valley cerise floors               1
floor wise designer kothi                              1
birla navya                                            1
kothi                                                  1
rajendra park sec 105                                  1
ansal heights                                          1
landmark house                                         1
dlf the arbour                                         1
ansal florence super                                   1
cloudnine cottages                                     1
u block dlf phase 3 road no 21                         1
sector 15 part 2 rwa                                   1
nitin vihar                                            1
ansal                                                  1
ashok vihar phase iii extension                        1
rattan vihar rajendra park                             1
signature global city 63a                              1
dlf city plot phase 3                                  1
adani brahma samsara                                   1
sneh vihar                                             1
secter 16a daultabad faridabad house no 313            1
unitech south city                                     1
smart world orchard                                    1
suncity avenue 76                                      1
huda floor                                             1
huda                                                   1
private house                                          1
sector 57 huda                                         1
godrej meridien                                        1
ansal sushant lok 2                                    1
the laburnum                                           1
vatika independent floors                              1
arjun marg/ sector- 26 phase- 1/ golf course road      1
sector-17c                                             1
dlf pink town house                                    1
patel nager house no 927/5                             1
satya the legend                                       1
huda sector-56 gurgaon                                 1
independent house sector 45                            1
ashok vihar phase 3 gurgaon                            1
farrukhnagar                                           1
unitech greenwood city                                 1
vatika the seven lamps                                 1
ansal sushant lok                                      1
central park                                           1
signature global city 81                               1
signature global city                                  1
dlf floors phase 3                                     1
prem kunj                                              1
sheetla enclave                                        1
ss omnia                                               1
dlf garden city floors                                 1
mian wali                                              1
ansal celebrity homes                                  1
laxmi garden sector-11                                 1
huda housing board colony                              1
house number b-34                                      1
shree krishna homes                                    1
smart world gems                                       1
ganpati heights apartment                              1
hero homes                                             1
jacobpura gurugram                                     1
anand garden, sector-105                               1
ats tourmaline                                         1
rk excelo                                              1
dlf the grove                                          1
surendra homes dayanand colony                         1
bhawani enclave                                        1
om nagar, sector-11                                    1
all punjabi welfare association                        1
vatika sovereign next                                  1
manohar nagar                                          1
laxman vihar phase 2                                   1
anamika enclave                                        1
bhim nagar, sector 6                                   1
emaar mgf the palm drive                               1
tulip ivory                                            1
huda plots                                             1
shri shyam residency                                   1
rajendra park gurgaon                                  1
anshul                                                 1
huda plot sector 38                                    1
sare crescent parc royal greens phase 1                1
signature global park                                  1
vipul world                                            1
greenopolis                                            1
ansal esencia sovereign floors                         1
nirmal enclave, maruti kunj road                       1
jacob pura                                             1
mahavir pura                                           1
raj villas                                             1
sector 37                                              1
shivaji nagar residential                              1
bhim nagar society                                     1
my home                                                1
anant raj manor villas                                 1
dlf city plot phase 4                                  1
sai kripa floors 5                                     1
naman residency                                        1
krishna palace                                         1
surat nagar phase 2                                    1
huda flats                                             1
jacobpura                                              1
indiabulls centrum park                                1
madan puri                                             1
dlf gardencity enclave                                 1
row house                                              1
tulip yellow                                           1
Name: count, dtype: int64

In [143]:
df['society'].value_counts().shape

(186,)

In [144]:
df['society'] = df['society'].str.replace('nan', 'independent')

In [145]:
df['society'].value_counts()

society
independent                                          619
emaar mgf marbella                                    26
international city by sobha phase 2                   26
vipul tatvam villa                                    25
international city by sobha phase 1                   23
unitech uniworld resorts                              14
dlf city plots phase 2                                11
unitech espace                                        11
dlf city plots                                        11
eldeco mansionz                                        9
bptp visionnaire                                       8
uppal southend                                         8
not applicable                                         7
sushant lok 1 builder floors                           6
ansals palam vihar                                     6
experion windchants                                    5
dlf city phase 1                                       5
dlf new town heights                                   5
dlf alameda                                            4
unitech nirvana birch court                            4
unitech aspen greens                                   4
ansals florence villa                                  4
nul                                                    4
vatika india next                                      4
ansal sushant lok plots                                4
eros rosewood villas                                   3
bptp astaire gardens                                   3
bestech park view aindependentda                       3
huda ashok vihar phase                                 3
hans enclave                                           3
housing board colony                                   3
eros rosewood city                                     3
palam vihar extension west zone rwa                    3
malibu towne                                           3
sector 14 rwa                                          3
vatika signature villas                                3
ss aaron ville                                         3
rattan garden                                          3
silverglades tarudhan valley golf resort               3
tata primanti                                          3
puri diplomatic greens                                 3
dlf city plots phase 3                                 3
central park flower valley                             3
aindependentt raj estates                              3
nirvana country                                        2
iffco nagar and 17b rwa                                2
bhim garh kheri                                        2
sobha city                                             2
dlf south city 1                                       2
ardee city                                             2
ansal sushant residency                                2
unitech escape                                         2
satya the hermitage                                    2
suncity township                                       2
suncity essel towers                                   2
unitech deerwood chase                                 2
emaar the palm springs                                 2
project housing board colony                           2
ansal api esencia                                      2
ireo victory valley                                    2
ss hibiscus                                            2
saksham welfare association                            2
unitech palms south city 1                             2
bptp pedestal                                          2
luxury dlf city floors                                 2
rwa sector 46                                          2
sector 38 rwa                                          2
nirvana cedar crest                                    2
signature global city 92                               2
dlf city plots phase 4                                 2
project mianwali colony                                2
emaar emerald hills                                    2
spaze privy                                            2
shivpuri                                               2
ninex city                                             1
grover homes sec 4                                     1
4s aradhya homes                                       1
ansal api spanish court                                1
central park flower valley cerise floors               1
floor wise designer kothi                              1
birla navya                                            1
kothi                                                  1
rajendra park sec 105                                  1
ansal heights                                          1
landmark house                                         1
dlf the arbour                                         1
ansal florence super                                   1
cloudnine cottages                                     1
u block dlf phase 3 road no 21                         1
sector 15 part 2 rwa                                   1
nitin vihar                                            1
ansal                                                  1
ashok vihar phase iii extension                        1
rattan vihar rajendra park                             1
signature global city 63a                              1
dlf city plot phase 3                                  1
adani brahma samsara                                   1
sneh vihar                                             1
secter 16a daultabad faridabad house no 313            1
unitech south city                                     1
smart world orchard                                    1
suncity avenue 76                                      1
huda floor                                             1
huda                                                   1
private house                                          1
sector 57 huda                                         1
godrej meridien                                        1
ansal sushant lok 2                                    1
the laburnum                                           1
vatika independent floors                              1
arjun marg/ sector- 26 phase- 1/ golf course road      1
sector-17c                                             1
dlf pink town house                                    1
patel nager house no 927/5                             1
satya the legend                                       1
huda sector-56 gurgaon                                 1
independent house sector 45                            1
ashok vihar phase 3 gurgaon                            1
farrukhnagar                                           1
unitech greenwood city                                 1
vatika the seven lamps                                 1
ansal sushant lok                                      1
central park                                           1
signature global city 81                               1
signature global city                                  1
dlf floors phase 3                                     1
prem kunj                                              1
sheetla enclave                                        1
ss omnia                                               1
dlf garden city floors                                 1
mian wali                                              1
ansal celebrity homes                                  1
laxmi garden sector-11                                 1
huda housing board colony                              1
house number b-34                                      1
shree krishna homes                                    1
smart world gems                                       1
ganpati heights apartment                              1
hero homes                                             1
jacobpura gurugram                                     1
aindependentd garden, sector-105                       1
ats tourmaline                                         1
rk excelo                                              1
dlf the grove                                          1
surendra homes dayaindependentd colony                 1
bhawani enclave                                        1
om nagar, sector-11                                    1
all punjabi welfare association                        1
vatika sovereign next                                  1
manohar nagar                                          1
laxman vihar phase 2                                   1
anamika enclave                                        1
bhim nagar, sector 6                                   1
emaar mgf the palm drive                               1
tulip ivory                                            1
huda plots                                             1
shri shyam residency                                   1
rajendra park gurgaon                                  1
anshul                                                 1
huda plot sector 38                                    1
sare crescent parc royal greens phase 1                1
signature global park                                  1
vipul world                                            1
greenopolis                                            1
ansal esencia sovereign floors                         1
nirmal enclave, maruti kunj road                       1
jacob pura                                             1
mahavir pura                                           1
raj villas                                             1
sector 37                                              1
shivaji nagar residential                              1
bhim nagar society                                     1
my home                                                1
aindependentt raj manor villas                         1
dlf city plot phase 4                                  1
sai kripa floors 5                                     1
naman residency                                        1
krishna palace                                         1
surat nagar phase 2                                    1
huda flats                                             1
jacobpura                                              1
indiabulls centrum park                                1
madan puri                                             1
dlf gardencity enclave                                 1
row house                                              1
tulip yellow                                           1
Name: count, dtype: int64

In [146]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [147]:
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
5 Crore             13
4.5 Crore           13
70 Lac              13
8 Crore             13
50 Lac              13
75 Lac              13
8.5 Crore           12
7 Crore             12
85 Lac              12
1.5 Crore           11
4 Crore             11
10 Crore            10
Price on Request    10
45 Lac              10
2.25 Crore          10
2.5 Crore           10
60 Lac              10
90 Lac              10
9 Crore             10
9.5 Crore            9
12 Crore             9
80 Lac               9
1.7 Crore            9
2 Crore              9
1.1 Crore            9
1 Crore              8
6.75 Crore           8
11 Crore             8
1.6 Crore            8
4.6 Crore            8
1.3 Crore            7
95 Lac               7
12.5 Crore           7
3.75 Crore           7
1.2 Crore            7
55 Lac               7
2.1 Crore            7
65 Lac               7
40 Lac               7
1.35 Crore           7
1.15 Crore           6
10.5 Crore           6
4.25 Crore           6
7.5 Crore            6
16 Crore             6
3.25 Crore           6
2.95 Crore           6
5.7 Crore            6
2.75 Crore           6
13.5 Crore           6
3.6 Crore            6
1.45 Crore           6
6.25 Crore           6
38 Lac               5
3 Crore              5
4.75 Crore           5
15 Crore             5
35 Lac               5
5.6 Crore            5
1.8 Crore            5
1.25 Crore           5
2.8 Crore            5
7.25 Crore           5
42 Lac               4
2.4 Crore            4
1.65 Crore           4
4.35 Crore           4
4.7 Crore            4
18 Crore             4
9.25 Crore           4
37 Lac               4
5.25 Crore           4
1.4 Crore            4
8.25 Crore           4
5.75 Crore           4
11.5 Crore           4
6.8 Crore            4
17 Crore             4
3.2 Crore            4
5.8 Crore            4
13 Crore             4
3.3 Crore            4
1.16 Crore           3
2.3 Crore            3
82 Lac               3
1.9 Crore            3
5.65 Crore           3
7.35 Crore           3
4.3 Crore            3
92 Lac               3
1.85 Crore           3
34 Lac               3
3.4 Crore            3
32 Lac               3
49 Lac               3
5.15 Crore           3
62 Lac               3
8.4 Crore            3
2.2 Crore            3
19 Crore             3
4.45 Crore           3
6.95 Crore           3
6.4 Crore            3
20 Crore             3
1.95 Crore           3
3.1 Crore            3
7.2 Crore            3
2.9 Crore            3
1.55 Crore           3
3.85 Crore           3
9.9 Crore            2
11.75 Crore          2
7.1 Crore            2
4.95 Crore           2
14 Crore             2
8.49 Crore           2
1.05 Crore           2
3.51 Crore           2
3.35 Crore           2
89 Lac               2
10.85 Crore          2
26 Crore             2
58.25 Lac            2
3.65 Crore           2
10.55 Crore          2
15.5 Crore           2
3.15 Crore           2
2.15 Crore           2
6.3 Crore            2
2.55 Crore           2
11.25 Crore          2
36 Lac               2
66 Lac               2
48 Lac               2
1.75 Crore           2
11.95 Crore          2
67 Lac               2
58 Lac               2
19.5 Crore           2
3.05 Crore           2
3.55 Crore           2
30 Lac               2
10.45 Crore          2
6.15 Crore           1
2.47 Crore           1
55.11 Lac            1
3.7 Crore            1
8.45 Crore           1
4.4 Crore            1
99 Lac               1
2.65 Crore           1
1.27 Crore           1
11.29 Crore          1
7.05 Crore           1
4.31 Crore           1
18.4 Crore           1
3.69 Crore           1
10.3 Crore           1
9.4 Crore            1
7.3 Crore            1
18.5 Crore           1
5.85 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
4.02 Crore           1
5.1 Crore            1
3.9 Crore            1
2.01 Crore           1
5.88 Crore           1
52.75 Lac            1
46.75 Lac            1
12.25 Crore          1
11.3 Crore           1
8.48 Crore           1
11.58 Crore          1
3.49 Crore           1
8.2 Crore            1
61 Lac               1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
5.35 Crore           1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
4.99 Crore           1
9.8 Crore            1
5.51 Crore           1
9.01 Crore           1
4.15 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
1.04 Crore           1
9.85 Crore           1
1.18 Crore           1
15.1 Crore           1
5.9 Crore            1
3.99 Crore           1
22 Crore             1
47 Lac               1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
5.2 Crore            1
7.99 Crore           1
42.75 Lac            1
71 Lac               1
7.6 Crore            1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
10.75 Crore          1
29 Lac               1
4.12 Crore           1
52 Lac               1
4.49 Crore           1
53 Lac               1
7.5 Lac              1
2.58 Crore           1
7.49 Crore           1
22 Lac               1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
63 Lac               1
1.87 Crore           1
1.72 Crore           1
5.46 Crore           1
12.39 Crore          1
78 Lac               1
1.52 Crore           1
10.56 Crore          1
5.4 Crore            1
24 Lac               1
44 Lac               1
83 Lac               1
17.3 Crore           1
3.93 Crore           1
27 Lac               1
8.1 Crore            1
8.7 Crore            1
14.75 Crore          1
9.54 Crore           1
6.2 Crore            1
18.9 Crore           1
98 Lac               1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.12 Crore           1
6.81 Crore           1
8.81 Crore           1
8.9 Crore            1
7.69 Crore           1
59 Lac               1
1.39 Crore           1
3.87 Crore           1
15.5 Lac             1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
13 Lac               1
96 Lac               1
6.6 Crore            1
18.02 Crore          1
65.8 Lac             1
8.8 Crore            1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
2.98 Crore           1
Name: count, dtype: int64

In [148]:
df['price'].value_counts().shape

(302,)

In [149]:
df[df['price']=='Price on Request']

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
295,2 Bedroom House for sale in Sector 8 Gurgaon,independent,Price on Request,NaN,(74 sq.m.) Built-up Area,Built Up area: 800 (74.32 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 8 Gurgaon, Gurgaon, Haryana",1 Floors,NaN,undefined,NaN,"1 bath, semi-Furnished, at sector 8 location g...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",P69650298
296,3 Bedroom House for sale in Dharam Colony,independent,Price on Request,NaN,(93 sq.m.) Carpet Area,Carpet area: 1000 (92.9 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Dharam Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, at dharam colony location...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",U69650258
325,5 Bedroom House for sale in Laxman Vihar,independent,Price on Request,NaN,(167 sq.m.) Built-up Area,Built Up area: 1800 (167.23 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,NaN,"Phase 2, Laxman Vihar, Gurgaon, Haryana",2 Floors,North,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","8 bath, unfurnished, overlooking main road, no...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",Y69533924
326,3 Bedroom House for sale in Laxman Vihar,independent,Price on Request,NaN,(223 sq.m.) Built-up Area,Built Up area: 2400 (222.97 sq.m.)Carpet area:...,3 Bedrooms,4 Bathrooms,2 Balconies,NaN,"1248 B, Near Hanuman Mandir, Laxman Vihar, Gur...",2 Floors,NaN,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","4 bath, unfurnished, 1st floor (Of 2), 1 side ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",K69533336
402,7 Bedroom House for sale in Rajendra Park,independent,Price on Request,NaN,(585 sq.m.) Built-up Area,Built Up area: 700 (585.29 sq.m.),7 Bedrooms,6 Bathrooms,3 Balconies,NaN,"Rajendra Park, Gurgaon, Haryana",4 Floors,NaN,5 to 10 Year Old,NaN,"6 bath, furnished, 2 side open, at rajendra pa...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",K63723534
431,3 Bedroom House for sale in Ansal Plaza,independent,Price on Request,NaN,(40 sq.m.) Carpet Area,Carpet area: 429 (39.86 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Ansal Plaza, Sector 23, Ansal Plaza, Gurgaon, ...",4 Floors,NaN,undefined,NaN,Best in class property available at ansal plaz...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5...",V68785776
494,2 Bedroom House for sale in Sheetla Colony,independent,Price on Request,NaN,(42 sq.m.) Plot Area,Plot area 50(41.81 sq.m.)Built Up area: 720 sq...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sheetla Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, semi-Furnished, at sheetla colony loca...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5...",G68368434
569,5 Bedroom House for sale in Surat Nagar,independent,Price on Request,NaN,(54 sq.m.) Built-up Area,Built Up area: 65 (54.35 sq.m.),5 Bedrooms,2 Bathrooms,No Balcony,NaN,"Surat Nagar Phase 2, Sector 104, Surat Nagar, ...",2 Floors,NaN,undefined,NaN,5bhk residential house for resale in surat nag...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5...",L67904496
595,2 Bedroom House for sale in Dharam Colony Block E,independent,Price on Request,NaN,(84 sq.m.) Built-up Area,Built Up area: 900 (83.61 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Dharam Colony Block E, Gurgaon, Haryana",1 Floors,NaN,undefined,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","1 bath, unfurnished, ground floor (Of 1), at d...",NaN,NaN,NaN,T65452900
668,4 Bedroom House for sale in Madanpuri,independent,Price on Request,NaN,(167 sq.m.) Carpet Area,Carpet area: 1800 (167.23 sq.m.),4 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Madanpuri, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 1 side open, at madan pur...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",B64214338

In [150]:
df[df['price']=='price']

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating, property_id]
Index: []

In [151]:
df = df[df['price']!='Price on Request']

In [152]:
df.shape

(1072, 20)

In [153]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [154]:
df['price'].value_counts()

price
3.5 Crore      19
5.5 Crore      17
6.5 Crore      16
6 Crore        14
50 Lac         13
5 Crore        13
4.5 Crore      13
75 Lac         13
8 Crore        13
70 Lac         13
8.5 Crore      12
7 Crore        12
85 Lac         12
1.5 Crore      11
4 Crore        11
60 Lac         10
10 Crore       10
45 Lac         10
90 Lac         10
2.25 Crore     10
2.5 Crore      10
9 Crore        10
1.1 Crore       9
80 Lac          9
9.5 Crore       9
2 Crore         9
1.7 Crore       9
12 Crore        9
11 Crore        8
6.75 Crore      8
4.6 Crore       8
1 Crore         8
1.6 Crore       8
65 Lac          7
3.75 Crore      7
2.1 Crore       7
1.3 Crore       7
12.5 Crore      7
1.2 Crore       7
1.35 Crore      7
95 Lac          7
40 Lac          7
55 Lac          7
3.25 Crore      6
7.5 Crore       6
2.75 Crore      6
3.6 Crore       6
1.45 Crore      6
6.25 Crore      6
16 Crore        6
1.15 Crore      6
13.5 Crore      6
10.5 Crore      6
4.25 Crore      6
5.7 Crore       6
2.95 Crore      6
2.8 Crore       5
3 Crore         5
15 Crore        5
38 Lac          5
4.75 Crore      5
1.8 Crore       5
7.25 Crore      5
1.25 Crore      5
35 Lac          5
5.6 Crore       5
1.65 Crore      4
42 Lac          4
4.7 Crore       4
2.4 Crore       4
37 Lac          4
4.35 Crore      4
18 Crore        4
9.25 Crore      4
5.25 Crore      4
1.4 Crore       4
8.25 Crore      4
5.75 Crore      4
3.2 Crore       4
11.5 Crore      4
6.8 Crore       4
5.8 Crore       4
17 Crore        4
3.3 Crore       4
13 Crore        4
3.4 Crore       3
7.2 Crore       3
1.9 Crore       3
82 Lac          3
5.65 Crore      3
7.35 Crore      3
4.3 Crore       3
92 Lac          3
62 Lac          3
1.16 Crore      3
34 Lac          3
32 Lac          3
8.4 Crore       3
5.15 Crore      3
49 Lac          3
1.85 Crore      3
2.2 Crore       3
2.3 Crore       3
3.1 Crore       3
3.85 Crore      3
6.4 Crore       3
1.95 Crore      3
19 Crore        3
6.95 Crore      3
20 Crore        3
4.45 Crore      3
1.55 Crore      3
2.9 Crore       3
4.95 Crore      2
7.1 Crore       2
14 Crore        2
8.49 Crore      2
1.05 Crore      2
3.51 Crore      2
11.75 Crore     2
2.15 Crore      2
26 Crore        2
10.85 Crore     2
58.25 Lac       2
3.65 Crore      2
10.55 Crore     2
15.5 Crore      2
3.35 Crore      2
3.15 Crore      2
89 Lac          2
9.9 Crore       2
6.3 Crore       2
66 Lac          2
3.05 Crore      2
36 Lac          2
10.45 Crore     2
19.5 Crore      2
67 Lac          2
48 Lac          2
1.75 Crore      2
2.55 Crore      2
58 Lac          2
30 Lac          2
3.55 Crore      2
11.25 Crore     2
11.95 Crore     2
1.83 Crore      1
99 Lac          1
5.9 Crore       1
2.47 Crore      1
18.5 Crore      1
3.7 Crore       1
18.4 Crore      1
4.4 Crore       1
2.65 Crore      1
3.9 Crore       1
1.27 Crore      1
11.29 Crore     1
61 Lac          1
4.31 Crore      1
7.3 Crore       1
11.58 Crore     1
4.02 Crore      1
27.5 Crore      1
5.1 Crore       1
6.15 Crore      1
8.31 Crore      1
8.45 Crore      1
10.3 Crore      1
9.4 Crore       1
8.48 Crore      1
6.21 Crore      1
3.69 Crore      1
12.25 Crore     1
46.75 Lac       1
52.75 Lac       1
5.88 Crore      1
11.3 Crore      1
2.01 Crore      1
7.05 Crore      1
55.11 Lac       1
8.2 Crore       1
4.99 Crore      1
8.6 Crore       1
9.55 Crore      1
2.35 Crore      1
18.25 Crore     1
5.3 Crore       1
5.35 Crore      1
10.8 Crore      1
31.5 Crore      1
4.1 Crore       1
7.65 Crore      1
6.46 Crore      1
6.44 Crore      1
7.8 Crore       1
3.8 Crore       1
7.45 Crore      1
7.42 Crore      1
6.09 Crore      1
5.85 Crore      1
9.8 Crore       1
4.15 Crore      1
9.01 Crore      1
3.49 Crore      1
2.99 Crore      1
9.19 Crore      1
1.64 Crore      1
9.35 Crore      1
4.05 Crore      1
8.75 Crore      1
23 Crore        1
2.45 Crore      1
7.85 Crore      1
25 Crore        1
2.68 Crore      1
2.7 Crore       1
1.04 Crore      1
9.85 Crore      1
1.18 Crore      1
15.1 Crore      1
5.51 Crore      1
3.99 Crore      1
22 Crore        1
47 Lac          1
4.65 Crore      1
6.1 Crore       1
68 Lac          1
1.07 Crore      1
5.2 Crore       1
7.99 Crore      1
42.75 Lac       1
71 Lac          1
7.6 Crore       1
15.5 Lac        1
52.5 Lac        1
1.44 Crore      1
3.71 Crore      1
18 Lac          1
3.08 Crore      1
10.75 Crore     1
5.4 Crore       1
52 Lac          1
4.49 Crore      1
53 Lac          1
7.5 Lac         1
2.58 Crore      1
22 Lac          1
7.49 Crore      1
8.95 Crore      1
13.2 Crore      1
51 Lac          1
63 Lac          1
4.12 Crore      1
1.72 Crore      1
5.46 Crore      1
78 Lac          1
1.52 Crore      1
12.39 Crore     1
10.56 Crore     1
1.87 Crore      1
29 Lac          1
24 Lac          1
44 Lac          1
17.3 Crore      1
3.93 Crore      1
27 Lac          1
8.1 Crore       1
8.7 Crore       1
14.75 Crore     1
9.54 Crore      1
6.2 Crore       1
18.9 Crore      1
83 Lac          1
24 Crore        1
7.46 Crore      1
59.95 Lac       1
3.12 Crore      1
6.81 Crore      1
8.81 Crore      1
8.9 Crore       1
7.69 Crore      1
59 Lac          1
1.39 Crore      1
3.87 Crore      1
98 Lac          1
47.5 Lac        1
3.09 Crore      1
74 Lac          1
69 Lac          1
2.43 Crore      1
13 Lac          1
96 Lac          1
6.6 Crore       1
18.02 Crore     1
65.8 Lac        1
8.8 Crore       1
1.34 Crore      1
46 Lac          1
2.6 Crore       1
2.98 Crore      1
Name: count, dtype: int64

In [155]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100, 2)
        else:
            return round(float(x[0]),2)

In [156]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [157]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [158]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     12
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 13,333/sq.ft.      7
₹ 37,037/sq.ft.      7
₹ 26,667/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 30,556/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 8,000/sq.ft.       6
₹ 9,444/sq.ft.       5
₹ 5,000/sq.ft.       5
₹ 8,889/sq.ft.       5
₹ 23,333/sq.ft.      5
₹ 23,148/sq.ft.      5
₹ 11,100/sq.ft.      5
₹ 32,407/sq.ft.      5
₹ 6,944/sq.ft.       4
₹ 15,625/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 25,000/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 35,000/sq.ft.      4
₹ 18,889/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 33,951/sq.ft.      3
₹ 12,000/sq.ft.      3
₹ 23,457/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 17,037/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 13,889/sq.ft.      3
₹ 44,444/sq.ft.      3
₹ 14,815/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 10,556/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 20,000/sq.ft.      3
₹ 16,058/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 29,880/sq.ft.      3
₹ 100,000/sq.ft.     3
₹ 8,235/sq.ft.       3
₹ 60,000/sq.ft.      3
₹ 50,000/sq.ft.      3
₹ 25,926/sq.ft.      3
₹ 9,259/sq.ft.       3
₹ 7,500/sq.ft.       3
₹ 15,555/sq.ft.      3
₹ 12,222/sq.ft.      3
₹ 32,222/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 11,852/sq.ft.      2
₹ 21,242/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 7,777/sq.ft.       2
₹ 16,975/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 7,407/sq.ft.       2
₹ 9,634/sq.ft.       2
₹ 8,888/sq.ft.       2
₹ 59,259/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 20,635/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 9,000/sq.ft.       2
₹ 15,257/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 29,630/sq.ft.      2
₹ 24,155/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 12,500/sq.ft.      2
₹ 45,833/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 24,845/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 1,859/sq.ft.       2
₹ 25,535/sq.ft.      2
₹ 7,718/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 24,500/sq.ft.      2
₹ 35,185/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 17,778/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 27,461/sq.ft.      2
₹ 42,194/sq.ft.      2
₹ 5,333/sq.ft.       2
₹ 55,000/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 7,619/sq.ft.       2
₹ 38,760/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 10,579/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 15,278/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 201,388/sq.ft.     2
₹ 13,910/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 19,708/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 21,759/sq.ft.      2
₹ 13,622/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 18,928/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 17,187/sq.ft.      2
₹ 24,455/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 33,592/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 18,444/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 39,530/sq.ft.      1
₹ 178,571/sq.ft.     1
₹ 20,988/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 18,626/sq.ft.      1
₹ 22,812/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 21,296/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 17,662/sq.ft.      1
₹ 42,054/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 20,068/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 18,888/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 20,741/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 38,889/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 8,920/sq.ft.       1
₹ 241,666/sq.ft.     1
₹ 6,938/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 28,898/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 20,444/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 17,857/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 14,166/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 18,658/sq.ft.      1
₹ 10,484/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 8,127/sq.ft.       1
₹ 7,555/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 7,539/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 9,390/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 6,800/sq.ft.       1
₹ 7,333/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 10,610/sq.ft.      1
₹ 8,155/sq.ft.       1
₹ 27,191/sq.ft.      1
₹ 15,926/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 23,889/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 36,911/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 5,777/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 5,128/sq.ft.       1
₹ 24,074/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 9,615/sq.ft.       1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 25,463/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 19,360/sq.ft.      1
₹ 23,556/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 9,349/sq.ft.       1
₹ 23,504/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 21,786/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 12,393/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 19,293/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 14,667/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 47,803/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 33,665/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 28,787/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 33,129/sq.ft.      1
₹ 13,992/sq.ft.      1
₹ 31,008/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 26,502/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 7,827/sq.ft.       1
₹ 19,820/sq.ft.      1
₹ 18,333/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 28,233/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 40,850/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 30,864/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 16,056/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 16,066/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 19,645/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 20,115/sq.ft.      1
₹ 6,702/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 138,888/sq.ft.     1
₹ 7,666/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 8,007/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 481/sq.ft.         1
₹ 3,452/sq.ft.       1
₹ 24,444/sq.ft.      1
₹ 13,071/sq.ft.      1
₹ 102,941/sq.ft.     1
₹ 29,321/sq.ft.      1
₹ 24,912/sq.ft.      1
₹ 255,555/sq.ft.     1
₹ 4,333/sq.ft.       1
₹ 11,784/sq.ft.      1
₹ 13,359/sq.ft.      1
₹ 197,080/sq.ft.     1
₹ 13,131/sq.ft.      1
₹ 74,074/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,486/sq.ft.       1
₹ 7,589/sq.ft.       1
₹ 8,181/sq.ft.       1
₹ 10,089/sq.ft.      1
₹ 8,500/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 21,667/sq.ft.      1
₹ 20,425/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 17,695/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 12,592/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 8,411/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 43,333/sq.ft.      1
₹ 7,309/sq.ft.       1
₹ 6,981/sq.ft.       1
₹ 122,222/sq.ft.     1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 21,000/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 13,542/sq.ft.      1
₹ 28,490/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 4,074/sq.ft.       1
₹ 630/sq.ft.         1
₹ 86,567/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 14,729/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 38,667/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 11,904/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 183,333/sq.ft.     1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 105,751/sq.ft.     1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 19,818/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 6,481/sq.ft.       1
₹ 13,499/sq.ft.      1
₹ 8,642/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 232/sq.ft.         1
₹ 218,750/sq.ft.     1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 37,313/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 10,122/sq.ft.      1
₹ 98,214/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 14,323/sq.ft.      1
₹ 181,818/sq.ft.     1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,397/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 3,904/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 17,500/sq.ft.      1
₹ 14,720/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 20,062/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 7,576/sq.ft.       1
₹ 3,874/sq.ft.       1
₹ 11,555/sq.ft.      1
₹ 6,567/sq.ft.       1
₹ 66,666/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 12,778/sq.ft.      1
₹ 15,097/sq.ft.      1
₹ 10,134/sq.ft.      1
₹ 9,375/sq.ft.       1
₹ 4,400/sq.ft.       1
₹ 13,636/sq.ft.      1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 21,111/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 19,869/sq.ft.      1
₹ 8,796/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 5,666/sq.ft.       1
₹ 11,718/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 53,125/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 40,909/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 4,808/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 5,658/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 151/sq.ft.         1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 35,494/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 315,789/sq.ft.     1
₹ 6,790/sq.ft.       1
₹ 73,333/sq.ft.      1
₹ 5,778/sq.ft.       1
₹ 26,000/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 6,111/sq.ft.       1
₹ 125,000/sq.ft.     1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 120,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 13,034/sq.ft.      1
Name: count, dtype: int64

In [159]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [160]:
df['price_per_sqft'].value_counts()

price_per_sqft
22222.0     14
11111.0     12
33333.0     11
10000.0     10
13333.0      7
37037.0      7
26667.0      6
26235.0      6
30556.0      6
31481.0      6
8000.0       6
9444.0       5
5000.0       5
8889.0       5
23333.0      5
23148.0      5
11100.0      5
32407.0      5
6944.0       4
15625.0      4
24691.0      4
34722.0      4
21605.0      4
25000.0      4
9722.0       4
35000.0      4
18889.0      4
27778.0      4
33951.0      3
12000.0      3
23457.0      3
6666.0       3
17037.0      3
8444.0       3
13889.0      3
44444.0      3
14815.0      3
11250.0      3
10556.0      3
8333.0       3
20000.0      3
16058.0      3
5555.0       3
29880.0      3
100000.0     3
8235.0       3
60000.0      3
50000.0      3
25926.0      3
9259.0       3
7500.0       3
15555.0      3
12222.0      3
32222.0      3
36111.0      3
11852.0      2
21242.0      2
20833.0      2
10518.0      2
10753.0      2
7777.0       2
16975.0      2
32328.0      2
14444.0      2
10101.0      2
7407.0       2
9634.0       2
8888.0       2
59259.0      2
12444.0      2
20635.0      2
26852.0      2
9000.0       2
15257.0      2
3500.0       2
29630.0      2
24155.0      2
42222.0      2
38194.0      2
12500.0      2
45833.0      2
26389.0      2
12963.0      2
24845.0      2
11574.0      2
39841.0      2
48148.0      2
1859.0       2
25535.0      2
7718.0       2
7058.0       2
24500.0      2
35185.0      2
25562.0      2
17284.0      2
17778.0      2
13000.0      2
24306.0      2
27461.0      2
42194.0      2
5333.0       2
55000.0      2
21124.0      2
7619.0       2
38760.0      2
38095.0      2
35556.0      2
38580.0      2
32963.0      2
10783.0      2
12342.0      2
10579.0      2
19000.0      2
15278.0      2
3857.0       2
201388.0     2
13910.0      2
15700.0      2
4444.0       2
19708.0      2
16039.0      2
75000.0      2
21759.0      2
13622.0      2
12027.0      2
18928.0      2
37627.0      2
17187.0      2
24455.0      1
13492.0      1
21495.0      1
11157.0      1
19268.0      1
33592.0      1
15989.0      1
27222.0      1
23693.0      1
23704.0      1
20940.0      1
11600.0      1
31686.0      1
63554.0      1
32253.0      1
18444.0      1
57206.0      1
23061.0      1
10601.0      1
194444.0     1
39530.0      1
178571.0     1
20988.0      1
23000.0      1
24171.0      1
29697.0      1
26298.0      1
24366.0      1
6778.0       1
18626.0      1
22812.0      1
16569.0      1
21296.0      1
400000.0     1
17662.0      1
42054.0      1
13501.0      1
261194.0     1
20068.0      1
22429.0      1
18888.0      1
82540.0      1
26428.0      1
13178.0      1
20741.0      1
1560.0       1
38889.0      1
32562.0      1
8920.0       1
241666.0     1
6938.0       1
10067.0      1
1649.0       1
28898.0      1
28200.0      1
7168.0       1
20444.0      1
6289.0       1
17857.0      1
7000.0       1
14166.0      1
30968.0      1
18658.0      1
10484.0      1
160000.0     1
8127.0       1
7555.0       1
49500.0      1
13030.0      1
308333.0     1
7539.0       1
84000.0      1
7302.0       1
9390.0       1
7479.0       1
7400.0       1
16003.0      1
9103.0       1
7727.0       1
45710.0      1
8702.0       1
5950.0       1
26973.0      1
13750.0      1
6000.0       1
14890.0      1
9210.0       1
6800.0       1
7333.0       1
8101.0       1
14184.0      1
4260.0       1
10582.0      1
10610.0      1
8155.0       1
27191.0      1
15926.0      1
34307.0      1
51864.0      1
44265.0      1
29444.0      1
39074.0      1
38734.0      1
23442.0      1
41833.0      1
600000.0     1
23889.0      1
10260.0      1
31915.0      1
11102.0      1
8866.0       1
36911.0      1
15444.0      1
11240.0      1
15437.0      1
14351.0      1
14285.0      1
5777.0       1
10591.0      1
5128.0       1
24074.0      1
5160.0       1
144444.0     1
9615.0       1
6813.0       1
15046.0      1
11583.0      1
6034.0       1
10085.0      1
40611.0      1
29629.0      1
10740.0      1
17980.0      1
19737.0      1
5093.0       1
25463.0      1
7007.0       1
35294.0      1
8254.0       1
19360.0      1
23556.0      1
23437.0      1
27160.0      1
41315.0      1
3786.0       1
9349.0       1
23504.0      1
234375.0     1
21786.0      1
15432.0      1
21251.0      1
35530.0      1
27390.0      1
22046.0      1
27132.0      1
22855.0      1
40741.0      1
29333.0      1
290948.0     1
12393.0      1
22331.0      1
30728.0      1
18250.0      1
2716.0       1
19293.0      1
11428.0      1
22184.0      1
30247.0      1
20370.0      1
31666.0      1
283333.0     1
18008.0      1
12285.0      1
20599.0      1
16319.0      1
173992.0     1
21367.0      1
20299.0      1
41818.0      1
19231.0      1
6875.0       1
14667.0      1
14787.0      1
20317.0      1
18088.0      1
16600.0      1
20566.0      1
16071.0      1
51440.0      1
28782.0      1
34491.0      1
34351.0      1
47803.0      1
6230.0       1
33665.0      1
20349.0      1
21219.0      1
24202.0      1
23870.0      1
20026.0      1
28787.0      1
12551.0      1
33129.0      1
13992.0      1
31008.0      1
23240.0      1
33404.0      1
32870.0      1
24005.0      1
19125.0      1
18885.0      1
15000.0      1
18814.0      1
14000.0      1
266666.0     1
26502.0      1
18808.0      1
10838.0      1
19847.0      1
12037.0      1
17820.0      1
24390.0      1
26063.0      1
79365.0      1
23932.0      1
24573.0      1
24510.0      1
38986.0      1
55556.0      1
16666.0      1
43210.0      1
31926.0      1
38611.0      1
27911.0      1
29022.0      1
12837.0      1
12198.0      1
35741.0      1
7827.0       1
19820.0      1
18333.0      1
10035.0      1
28841.0      1
26615.0      1
62222.0      1
6597.0       1
7870.0       1
28233.0      1
27083.0      1
31444.0      1
34846.0      1
40000.0      1
40850.0      1
26111.0      1
31790.0      1
235376.0     1
29293.0      1
16004.0      1
27333.0      1
17624.0      1
30864.0      1
161849.0     1
16056.0      1
17707.0      1
10926.0      1
19608.0      1
8089.0       1
6849.0       1
19607.0      1
15111.0      1
1087.0       1
16066.0      1
31111.0      1
21097.0      1
25556.0      1
7756.0       1
21825.0      1
16577.0      1
17706.0      1
29074.0      1
37778.0      1
17213.0      1
19645.0      1
18620.0      1
17014.0      1
7750.0       1
7172.0       1
29638.0      1
8137.0       1
7582.0       1
18605.0      1
34568.0      1
20769.0      1
13513.0      1
28549.0      1
36883.0      1
27871.0      1
35109.0      1
17692.0      1
38022.0      1
25309.0      1
16990.0      1
14222.0      1
16388.0      1
22075.0      1
11666.0      1
47167.0      1
7937.0       1
20197.0      1
34037.0      1
10123.0      1
28858.0      1
4877.0       1
20115.0      1
6702.0       1
5698.0       1
24214.0      1
26613.0      1
138888.0     1
7666.0       1
4666.0       1
7778.0       1
40775.0      1
99173.0      1
6172.0       1
9111.0       1
80357.0      1
4117.0       1
7308.0       1
8701.0       1
2296.0       1
9793.0       1
6250.0       1
28283.0      1
8007.0       1
11717.0      1
8928.0       1
481.0        1
3452.0       1
24444.0      1
13071.0      1
102941.0     1
29321.0      1
24912.0      1
255555.0     1
4333.0       1
11784.0      1
13359.0      1
197080.0     1
13131.0      1
74074.0      1
10233.0      1
8878.0       1
14286.0      1
8486.0       1
7589.0       1
8181.0       1
10089.0      1
8500.0       1
9333.0       1
21667.0      1
20425.0      1
5472.0       1
57692.0      1
10482.0      1
25386.0      1
8735.0       1
18667.0      1
2525.0       1
17695.0      1
21519.0      1
17817.0      1
2.0          1
6173.0       1
13888.0      1
8697.0       1
90000.0      1
12592.0      1
7280.0       1
15384.0      1
7843.0       1
29336.0      1
10288.0      1
11284.0      1
11029.0      1
10277.0      1
8518.0       1
10555.0      1
557.0        1
8947.0       1
39265.0      1
6083.0       1
230547.0     1
8411.0       1
32291.0      1
41666.0      1
43333.0      1
7309.0       1
6981.0       1
122222.0     1
19097.0      1
7290.0       1
27741.0      1
43534.0      1
45889.0      1
20690.0      1
29716.0      1
16378.0      1
37777.0      1
12519.0      1
27971.0      1
21000.0      1
13909.0      1
35400.0      1
13623.0      1
13331.0      1
40135.0      1
13542.0      1
28490.0      1
16999.0      1
24170.0      1
38251.0      1
43066.0      1
53763.0      1
39062.0      1
48889.0      1
38150.0      1
10077.0      1
34083.0      1
33200.0      1
14914.0      1
29861.0      1
41762.0      1
15451.0      1
12938.0      1
9374.0       1
13410.0      1
32593.0      1
16244.0      1
10714.0      1
25111.0      1
17650.0      1
26423.0      1
8916.0       1
36667.0      1
9028.0       1
4074.0       1
630.0        1
86567.0      1
92857.0      1
88157.0      1
29974.0      1
2778.0       1
46906.0      1
23699.0      1
25960.0      1
28424.0      1
4490.0       1
14729.0      1
24280.0      1
25514.0      1
10463.0      1
12593.0      1
18750.0      1
27793.0      1
22006.0      1
28760.0      1
41615.0      1
38703.0      1
12828.0      1
12842.0      1
8557.0       1
16428.0      1
13519.0      1
42032.0      1
24069.0      1
14650.0      1
13778.0      1
21250.0      1
38667.0      1
20323.0      1
20359.0      1
5833.0       1
6707.0       1
11904.0      1
9135.0       1
7111.0       1
8012.0       1
183333.0     1
10142.0      1
8125.0       1
14583.0      1
11538.0      1
8730.0       1
105751.0     1
8230.0       1
13095.0      1
29311.0      1
30384.0      1
19818.0      1
1992.0       1
245398.0     1
6481.0       1
13499.0      1
8642.0       1
11556.0      1
10378.0      1
11888.0      1
32258.0      1
16389.0      1
31506.0      1
12820.0      1
229885.0     1
12400.0      1
232.0        1
218750.0     1
54794.0      1
14245.0      1
6367.0       1
37313.0      1
90909.0      1
10122.0      1
98214.0      1
7820.0       1
11693.0      1
14323.0      1
181818.0     1
26620.0      1
9500.0       1
17937.0      1
3254.0       1
4583.0       1
21875.0      1
16667.0      1
7075.0       1
8078.0       1
4251.0       1
17584.0      1
5397.0       1
9074.0       1
5583.0       1
3519.0       1
11194.0      1
4222.0       1
3904.0       1
4000.0       1
17500.0      1
14720.0      1
5664.0       1
19753.0      1
76000.0      1
63492.0      1
2500.0       1
6667.0       1
3704.0       1
12777.0      1
6648.0       1
11407.0      1
20233.0      1
20062.0      1
11494.0      1
25543.0      1
12343.0      1
16892.0      1
7576.0       1
3874.0       1
11555.0      1
6567.0       1
66666.0      1
8386.0       1
12778.0      1
15097.0      1
10134.0      1
9375.0       1
4400.0       1
13636.0      1
28674.0      1
9725.0       1
21111.0      1
10784.0      1
12162.0      1
8910.0       1
19869.0      1
8796.0       1
7522.0       1
22068.0      1
5666.0       1
11718.0      1
7627.0       1
53125.0      1
17900.0      1
39886.0      1
126865.0     1
40909.0      1
27155.0      1
14492.0      1
14045.0      1
10804.0      1
14167.0      1
13157.0      1
5888.0       1
7875.0       1
9654.0       1
4808.0       1
8222.0       1
11273.0      1
5658.0       1
24545.0      1
7701.0       1
14072.0      1
10224.0      1
3285.0       1
74000.0      1
27139.0      1
23662.0      1
17574.0      1
9091.0       1
23557.0      1
105263.0     1
21195.0      1
151.0        1
25103.0      1
14954.0      1
8784.0       1
6500.0       1
35494.0      1
11464.0      1
315789.0     1
6790.0       1
73333.0      1
5778.0       1
26000.0      1
24305.0      1
19286.0      1
22634.0      1
26570.0      1
6410.0       1
133079.0     1
6111.0       1
125000.0     1
78125.0      1
17955.0      1
7916.0       1
211111.0     1
80000.0      1
120000.0     1
22297.0      1
13034.0      1
Name: count, dtype: int64

In [161]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [162]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [163]:
df['bedRoom'].isnull().sum()

108

In [164]:
df = df[~df['bedRoom'].isnull()]

In [165]:
df.shape

(964, 20)

In [166]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [167]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [168]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
18 Bathrooms      4
13 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [169]:
df['bathroom'].isnull().sum()

0

In [174]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [176]:
df['bathroom'].value_counts()

bathroom
4     228
3     165
5     137
2     114
6      82
1      65
9      42
7      39
8      28
12     22
10     11
16      8
18      4
13      4
11      4
20      3
17      3
14      2
21      1
36      1
34      1
Name: count, dtype: int64

In [177]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [178]:
df['balcony'].value_counts()

balcony
3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: count, dtype: int64

In [179]:
df['balcony'].isnull().sum()

0

In [183]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).replace('No','0')

In [185]:
df['balcony'].value_counts()

balcony
3+    365
2     220
3     159
0     115
1     105
Name: count, dtype: int64

In [186]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [187]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Store Room,Study Room,Servant Room     8
Pooja Room,Servant Room,Store Room                7
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Servant Room,Pooja Room,Store Room                6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Pooja Room,Servant Room                5
Servant Room,Store Room,Pooja Room                4
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [188]:
df['additionalRoom'].isnull().sum()

386

In [190]:
df['additionalRoom'].fillna('not available', inplace=True)

In [191]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [192]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [193]:
df['floorNum'].value_counts()

floorNum
3 Floors     304
2 Floors     288
1 Floors     181
4 Floors     136
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: count, dtype: int64

In [194]:
df['floorNum'].isnull().sum()

19

In [198]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0)

In [199]:
df['floorNum'].value_counts()

floorNum
3     304
2     288
1     181
4     136
5       9
0       6
14      3
6       3
11      2
12      2
10      2
16      1
51      1
41      1
27      1
20      1
13      1
21      1
02      1
33      1
Name: count, dtype: int64

In [200]:
df['facing'].value_counts()

facing
East          178
North-East    158
North         109
West           75
North-West     44
South-East     39
South          34
South-West     24
Name: count, dtype: int64

In [201]:
df['facing'].isnull().sum()

303

In [203]:
df['facing'].fillna('NA',inplace=True)

In [204]:
df['area']= round((df['price']*10000000)/df['price_per_sqft'])

In [205]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [206]:
df.insert(loc=1, column='property_type', value='house')

In [207]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [208]:
df.shape

(964, 21)

In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 1090
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    int64
 8   bathroom         964 non-null    int64
 9   balcony          964 non-null    object
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    object
 13  facing           964 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
 20  property_id      964 non-null    object
dtypes: float64(3), int64(2), object(16)
memory usage: 165.7+ KB

In [210]:
df.to_csv('house_cleaned.csv', index=False)